pipeline {
    agent any
    tools {
      terraform 'terraform'
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/epalencia9/ELK-stack-2-docker/tree/main/ELK-Stack-deploy-dockercompose'
            }
        }
        stage('Terraform init') {
            steps {
                sh 'terraform init'
            }
        }
        stage('Terraform Apply') {
            steps {
                sh 'terraform apply --auto-approve'
            }
        }
    }
}
